=== icatproject/icat.server/icat3-jaxb/src/uk/icat3/jaxb/icatXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Damian Flannery (CCLRC) -->
<xs:schema xmlns:ic="http://www.icat.ac.uk" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" elementFormDefault="qualified" xml:lang="en" jaxb:version="2.0">
	<xs:annotation>
		<xs:appinfo>
			<jaxb:globalBindings>
				<jaxb:javaType name="java.util.Calendar" xmlType="xs:date" parseMethod="javax.xml.bind.DatatypeConverter.parseDate" printMethod="javax.xml.bind.DatatypeConverter.printDate"/>
			</jaxb:globalBindings>
		</xs:appinfo>
	</xs:annotation>
	<!-- ================================================================-->
	<xs:element name="icat" type="Icat"/>
	<!-- ================================================================-->
	<xs:complexType name="Icat">
		<xs:annotation>
			<xs:documentation> Top level group. 
				Must contain the group study. 
				Must have an an attribute, a version number which refere to the version of the ICAT schema.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="study" type="Study" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation> Study level group. 
				Must contain the group investigation. 
				All the others parameters are optional but if any is filled, a unique name must be provided. 
				(HELP Can I specify that in the schema?)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Study">
		<xs:annotation>
			<xs:documentation> Study level group. 
				Must contain the group investigation. 
				All the others parameters are optional but if any is filled, a unique name must be provided. 
				(HELP Can I specify that in the schema?)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="str255" minOccurs="0"/>
			<xs:element name="purpose" type="str4000" minOccurs="0"/>
			<xs:element name="status" type="Status" minOccurs="0">
				<xs:annotation>
					<xs:documentation> Correspond to the lookup table STUDY_STATUS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="related_material" type="str4000" minOccurs="0"/>
			<xs:element name="study_creation_date" type="timeStamp" minOccurs="0"/>
			<xs:element name="study_manager" type="str255" minOccurs="0"/>
			<xs:element name="investigation" type="Investigation" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation> Investigation level group. 
				Must contain inv_number, visit_id, instrument and the group dataset. 
				The three first parameters must define a unique key for that investigation.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!-- ................................................................-->
	<xs:simpleType name="Status">
		<xs:annotation>
			<xs:documentation>Correspond to the lookup table STUDY_STATUS</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="ONGOING"/>
			<xs:enumeration value="CLOSED"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- ================================================================-->
	<xs:complexType name="Investigation">
		<xs:sequence>
			<xs:element name="inv_number" type="Inv_Number">
				<xs:annotation>
					<xs:documentation>Investigation Number. 
				Not a lot of restriction for the moment. 
				String with a maximum of 255 characters to fit in the DB.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="visit_id" type="Visit_Id">
				<xs:annotation>
					<xs:documentation>Visit ID, used at DLS for proposal which span over several time slots. 
				Not a lot of restriction for the moment. 
				String with a maximum of 255 characters to fit in the DB.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="instrument" type="Instrument">
				<xs:annotation>
					<xs:documentation> Instrument List. It is facility dependant. 
				Correspond to the lookup table INSTRUMENT</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="title" type="str255" minOccurs="0"/>
			<xs:element name="investigator" type="Investigator" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation> This will contain the list of investigator attached to an investigation. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="inv_abstract" type="str4000" minOccurs="0"/>
			<xs:element name="inv_type" type="Inv_Type" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Correspond to the lookup table INVESTIGATION_TYPE</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="prev_inv_number" type="str255" minOccurs="0"/>
			<xs:element name="bcat_inv_str" type="str255" minOccurs="0"/>
			<xs:element name="grant_id" type="str255" minOccurs="0"/>
			<xs:element name="facility_cycle" type="Facility_Cycle" minOccurs="0">
				<xs:annotation>
					<xs:documentation> Correspond to the lookup table FACILITY_CYCLE
				New cycle will be added regularly, the checks will be done with pattern matching.
				We consider ISIS cycle like : cycle_06_03 or 2006/03</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="keyword" type="Keyword" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Correspond to the table KEYWORD </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="topic" type="Topic" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>This will hold the list of topic of the investigation. 
				At minimum, a topic need a name and in a list, they should be unique.
				If the topic_list exist, it should at least contain one topic.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="publication" type="Publication" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation> TBW </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="sample" type="Sample" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="dataset" type="Dataset" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation> TBW </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="trusted" type="xs:boolean" default="true"/>
	</xs:complexType>
	<!-- ................................................................-->
	<xs:simpleType name="Inv_Number">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Visit_Id">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Icat_Role">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--<xs:enumeration value="ADMIN"/>
			<xs:enumeration value="CREATOR"/>
			<xs:enumeration value="DELETER"/>
			<xs:enumeration value="DOWNLOADER"/>
			<xs:enumeration value="READER"/>						
			<xs:enumeration value="UPDATER"/>-->
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Instrument">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--<xs:enumeration value="HRPD"/>
			<xs:enumeration value="POLARIS"/>
			<xs:enumeration value="SXD"/>
			<xs:enumeration value="PEARL (HiPr)"/>
			<xs:enumeration value="GEM"/>
			<xs:enumeration value="PEARL(ENGIN)"/>
			<xs:enumeration value="SANDALS"/>
			<xs:enumeration value="GEM"/>
			<xs:enumeration value="LOQ"/>
			<xs:enumeration value="CRISP"/>
			<xs:enumeration value="SURF"/>
			<xs:enumeration value="HET"/>
			<xs:enumeration value="MARI"/>
			<xs:enumeration value="PRISMA"/>
			<xs:enumeration value="ROTAX"/>
			<xs:enumeration value="MAPS"/>
			<xs:enumeration value="ALF"/>
			<xs:enumeration value="IRIS"/>
			<xs:enumeration value="OSIRIS"/>
			<xs:enumeration value="TOSCA"/>
			<xs:enumeration value="VESUVIO"/>
			<xs:enumeration value="VESTA"/>
			<xs:enumeration value="MUSR"/>
			<xs:enumeration value="EMU"/>
			<xs:enumeration value="ARGUS"/>
			<xs:enumeration value="DEVA"/>
			<xs:enumeration value="RIKEN"/>
			<xs:enumeration value="KARMEN"/>
			<xs:enumeration value="INTER"/>
			<xs:enumeration value="OFFSPEC"/>
			<xs:enumeration value="POLREF"/>
			<xs:enumeration value="SANS-2D"/>
			<xs:enumeration value="NIMROD"/>
			<xs:enumeration value="WISH"/>
			<xs:enumeration value="LET"/>
			<xs:enumeration value="LMX"/>
			<xs:enumeration value="BOUNCE"/>
			<xs:enumeration value="SPIRAL"/>
			<xs:enumeration value="ZOOM"/>
			<xs:enumeration value="EXESS"/>
			<xs:enumeration value="HERBI"/>
			<xs:enumeration value="NESSIE"/>
			<xs:enumeration value="Astra TA-1"/>
			<xs:enumeration value="Astra TA-2"/>
			<xs:enumeration value="Astra-Gemini TA"/>
			<xs:enumeration value="Vulcan TA-1"/>
			<xs:enumeration value="Vulcan TA-2"/>
			<xs:enumeration value="Laser Microscope Laboratory"/>
			<xs:enumeration value="Nanosecond Science Laboratory"/>
			<xs:enumeration value="Ultrafast Spectroscopy Laboratory"/>
			<xs:enumeration value="I02-Macromolecular crystallography"/>
			<xs:enumeration value="I03-Macromolecular crystallography"/>
			<xs:enumeration value="I04-Macromolecular crystallography"/>
			<xs:enumeration value="I04.1-Macromolecular crystallography side station"/>
			<xs:enumeration value="I06-Nanoscience"/>
			<xs:enumeration value="I07-Surface and interface diffraction"/>
			<xs:enumeration value="I08-SISA: Surface and Interface Structural Analysis"/>
			<xs:enumeration value="I10-BLADE: Beamline for Advanced Dichroism Experiments"/>
			<xs:enumeration value="I11-High resolution powder diffraction"/>
			<xs:enumeration value="I12-JEEP: Joint Engineering, Environmental and Processing"/>
			<xs:enumeration value="I13L-X-Ray Imaging and Coherence"/>
			<xs:enumeration value="I15-Extreme conditions"/>
			<xs:enumeration value="I16-Materials and magnetism"/>
			<xs:enumeration value="B16-Test beamline"/>
			<xs:enumeration value="I18-Microfocus spectroscopy"/>
			<xs:enumeration value="B18-Core EXAFS"/>
			<xs:enumeration value="I19-Small molecule single crystal diffraction"/>
			<xs:enumeration value="I20-XAS-3:X-ray spectroscopy"/>
			<xs:enumeration value="I22-Non-crystalline diffraction"/>
			<xs:enumeration value="B22-Infrared Microspectroscopy"/>
			<xs:enumeration value="B23-Circular dichroism"/>
			<xs:enumeration value="I24-Microfocus macromolecular crystallography"/>
			<xs:enumeration value="gemini"/>-->
			<!-- ISIS instruments -->
			<!-- CLF instrument -->
			<!-- Diamond instrument -->
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Inv_Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--<xs:enumeration value="EXPERIMENT"/>
			<xs:enumeration value="CALIBRATION"/>
			<xs:enumeration value="ENGINEERING"/>
			<xs:enumeration value="TEST"/>-->
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Facility_Cycle">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--xs:pattern value="cycle_\p{Nd}{2}_\p{Nd}{2}|\p{Nd}{4}/\p{Nd}{2}"/ -->
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:complexType name="Keyword">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
		</xs:sequence>
	</xs:complexType>
	<!-- . . . . . . . . . . . . . . . . . . . -->
	<xs:complexType name="Topic">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
			<xs:element name="topic_level" type="xs:nonNegativeInteger" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ................................................................-->
	<xs:complexType name="Publication">
		<xs:sequence>
			<xs:element name="full_reference" type="str4000"/>
			<xs:element name="url" type="str255" minOccurs="0"/>
			<xs:element name="repository_id" type="str255" minOccurs="0"/>
			<xs:element name="repository" type="str4000" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ................................................................-->
	<xs:complexType name="Investigator">
        <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:choice minOccurs="1" maxOccurs="2">
                    <xs:element name="user_id" type="str255"/>
                    <xs:element name="affiliation_id" type="str255"/>
                </xs:choice>
                <xs:element name="role" type="str255"/>
                <xs:element name="privilege" type="Icat_Role" minOccurs="0"/>
            </xs:sequence>		
	</xs:complexType>

	<!-- ================================================================-->
	<xs:complexType name="Dataset">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
			<xs:element name="dataset_type" type="Dataset_Type">
				<xs:annotation>
					<xs:documentation> Correspond to the lookup table DATASET_TYPE </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="dataset_status" type="Dataset_Status" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Correspond to the lookup table DATASET_STATUS</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="description" type="str4000" minOccurs="0"/>
			<xs:element name="sample" type="Sample" minOccurs="0"/>
			<xs:element name="datafile" type="Datafile" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ................................................................-->
	<xs:simpleType name="Dataset_Type">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--<xs:enumeration value="EXPERIMENT_RAW"/>
			<xs:enumeration value="EXPERIMENT_CAL"/>
			<xs:enumeration value="EXPERIMENT_ENG"/>
			<xs:enumeration value="SOURCE_MONITORING"/>
			<xs:enumeration value="SAMPLE"/>
			<xs:enumeration value="TARGET"/>
			<xs:enumeration value="REDUCED"/>
			<xs:enumeration value="ANALYZED"/>
			<xs:enumeration value="SIMULATION"/>
			<xs:enumeration value="SPECIAL_CAL"/>
			<xs:enumeration value="SPECIAL_USER"/>
			<xs:enumeration value="LASER_SHOT"/>
			<xs:enumeration value="NOTES"/>-->
		</xs:restriction>
	</xs:simpleType>
	<!-- ................................................................-->
	<xs:simpleType name="Dataset_Status">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<!--<xs:enumeration value="EMPTY"/>
			<xs:enumeration value="MISSING_DATA"/>
			<xs:enumeration value="COMPLETE"/>-->
		</xs:restriction>
	</xs:simpleType>
	<!-- ================================================================-->
	<xs:complexType name="Sample">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
			<xs:element name="instance" type="str255" minOccurs="0"/>
			<xs:element name="chemical_formula" type="str255" minOccurs="0"/>
			<xs:element name="safety_information" type="str4000"/>
			<xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ================================================================-->
	<xs:complexType name="Parameter">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
			<xs:choice>
				<xs:element name="string_value" type="str4000"/>
				<xs:element name="numeric_value" type="xs:double"/>
			</xs:choice>
			<xs:element name="units" type="str255"/>
			<xs:element name="range_top" type="str255" minOccurs="0"/>
			<xs:element name="range_bottom" type="str255" minOccurs="0"/>
			<xs:element name="error" type="str255" minOccurs="0"/>
			<xs:element name="description" type="str4000" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ================================================================-->
	<xs:complexType name="Datafile">
		<xs:sequence>
			<xs:element name="name" type="str255"/>
			<xs:element name="location" type="str4000"/>
			<xs:element name="description" type="str4000" minOccurs="0"/>
			<xs:element name="datafile_version" type="str255" minOccurs="0"/>
			<xs:element name="datafile_version_comment" type="str255" minOccurs="0"/>
			<xs:element name="datafile_format" type="str255" minOccurs="0"/>
			<xs:element name="datafile_format_version" type="str255" minOccurs="0"/>
			<xs:element name="datafile_create_time" type="xs:dateTime"/>
			<xs:element name="datafile_modify_time" type="xs:dateTime"/>
			<xs:element name="file_size" type="xs:integer" minOccurs="0"/>
			<xs:element name="command" type="str4000" minOccurs="0"/>
			<xs:element name="checksum" type="str255" minOccurs="0"/>
			<xs:element name="signature" type="str4000" minOccurs="0"/>
			<xs:element name="parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- ================================================================-->
	<xs:simpleType name="Fedid">
		<xs:annotation>
			<xs:documentation>Fed-id as used for the Single Sign On. 
				2-3 lowercase characters followed by 2-3 digit.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\p{Ll}{2,3}\p{Nd}{2,3}"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- ================================================================-->
	<xs:simpleType name="timeStamp">
		<xs:annotation>
			<xs:documentation>DB timeStamp for the moment as a dateTime. CCYY-MM-DDThh:mm:ss</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<!-- ================================================================-->
	<xs:simpleType name="str255">
		<xs:annotation>
			<xs:documentation>String with a maximum of 255 characters to fit in the DB.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- ================================================================-->
	<xs:simpleType name="str4000">
		<xs:annotation>
			<xs:documentation>String with a maximum of 4000 characters to fit in the DB.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="4000"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== icatproject/icat.server/icat3-jaxb/src/test/data/Muon_00018.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<icat version="1.0 RC6" xsi:noNamespaceSchemaLocation="icatXSD.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<study>
<name>DEVA_1994</name>
<purpose>Group all Investigation per instrument and per year.</purpose>
<status>ONGOING</status>
<study_creation_date>2007-09-13T12:57:59</study_creation_date>
<investigation trusted="false">
<inv_number>n/a</inv_number>
<visit_id>1</visit_id>
<instrument>DEVA</instrument>
<title>Temperature = 295 K, Magnetic Field = 0 Gauss, Sample = ALUM</title>
<inv_type>EXPERIMENT</inv_type>
<bcat_inv_str>n/a</bcat_inv_str>
<dataset>
<name>Default</name>
<dataset_type>EXPERIMENT_RAW</dataset_type>
<dataset_status>COMPLETE</dataset_status>
<description> Title =Temperature = 295 K, Magnetic Field = 0 Gauss, Sample = ALUM Note =First MCS run on DEVA  slits 20</description>
<sample>
<name>ALUMINIUM</name>
<instance>0</instance>
<chemical_formula>ALUMINIUM</chemical_formula>
<safety_information>No information available.</safety_information>
<parameter>
<name>sample_shape</name>
<string_value>n/a</string_value>
<units>N/A</units></parameter>
<parameter>
<name>sample_situation</name>
<string_value>n/a</string_value>
<units>N/A</units></parameter></sample>
<datafile>
<name>00018.nxs</name>
<location>test_data/Muon/00018.nxs</location>
<description>Temperature = 295 K, Magnetic Field = 0 Gauss, Sample = ALUM</description>
<datafile_version>1.0</datafile_version>
<datafile_version_comment>First version</datafile_version_comment>
<datafile_format>NeXus</datafile_format>
<datafile_format_version>1.3.2</datafile_format_version>
<datafile_create_time>1994-06-07T14:32:05</datafile_create_time>
<datafile_modify_time>2007-08-21T12:58:24</datafile_modify_time>
<file_size>43352</file_size>
<parameter>
<name>run_number</name>
<numeric_value>0</numeric_value>
<units>N/A</units>
<description>Run Number</description></parameter>
<parameter>
<name>nexus_version</name>
<string_value>1.3.2</string_value>
<units>N/A</units>
<description>NeXus version used to create the file.</description></parameter>
<parameter>
<name>program_name</name>
<string_value>MCS</string_value>
<units>N/A</units>
<description>Name of creating program.</description></parameter>
<parameter>
<name>program_version</name>
<string_value>RC</string_value>
<units>N/A</units>
<description>version of creating program.</description></parameter>
<parameter>
<name>start_date</name>
<string_value>1994-06-07 14:32:05+0000</string_value>
<units>yyyy-MM-dd HH:mm:ss</units>
<description>Start Time of the dataset.</description></parameter>
<parameter>
<name>finish_date</name>
<string_value>1994-06-07 17:06:16+0000</string_value>
<units>yyyy-MM-dd HH:mm:ss</units>
<description>Start Time of the dataset.</description></parameter>
<parameter>
<name>run_duration</name>
<numeric_value>9251</numeric_value>
<units>seconds</units>
<description>Calculated duration.</description></parameter>
<parameter>
<name>switching_states</name>
<string_value>1</string_value>
<units>N/A</units>
<description>1 = Normal data collection, 2 = Red/Green mode</description></parameter>
<parameter>
<name>sample_temperature_setting</name>
<numeric_value>295.000000</numeric_value>
<units>kelvin</units>
<description>Desired temperature</description></parameter>
<parameter>
<name>sample_magnetic_field_setting</name>
<numeric_value>0.000000</numeric_value>
<units>gauss</units>
<description>Desired Magnetic field</description></parameter>
<parameter>
<name>sample_magnetic_field_state</name>
<string_value>n/a</string_value>
<units>N/A</units>
<description>Magnetic field mode, e.g. TF</description></parameter>
<parameter>
<name>detector_orientation</name>
<string_value>l</string_value>
<units>N/A</units>
<description>Detector arrangement. longitudinal 'l' or Transverse 't'</description></parameter>
<parameter>
<name>collimator_type</name>
<string_value>Slits</string_value>
<units>N/A</units>
<description>Collimator type. e.g. slits</description></parameter>
<parameter>
<name>source_total_count</name>
<numeric_value>7.840218</numeric_value>
<units>Mev</units>
<description>Total number of counts.</description></parameter>
<parameter>
<name>source_daereads</name>
<numeric_value>443</numeric_value>
<units>N/A</units>
<description>number of readout from the DAE.</description></parameter>
<parameter>
<name>source_frames</name>
<numeric_value>443000</numeric_value>
<units>N/A</units>
<description>ISIS frames collected on each DAE read.</description></parameter>
<parameter>
<name>data_avg_counts</name>
<numeric_value>0</numeric_value>
<units>counts</units>
<description>Average of number of counts in histogram_data_1.</description></parameter>
<parameter>
<name>data_std_counts</name>
<numeric_value>3499.61</numeric_value>
<units>counts</units>
<description>Standard deviation of number of counts in histogram_data_1.</description></parameter>
<parameter>
<name>histogram_resolution</name>
<numeric_value>16000.000000</numeric_value>
<units>picoseconds</units>
<description>Histogram resolution. set to 0 if not applicable.</description></parameter>
<parameter>
<name>time_zero</name>
<numeric_value>0.000000</numeric_value>
<units>microseconds</units>
<description>Time zero for muon measurement.</description></parameter>
<parameter>
<name>bcat_inv_str</name>
<string_value>n/a</string_value>
<units>N/A</units></parameter></datafile></dataset></investigation></study></icat>
